### PR TITLE
Add roberta-base and change to hugging face patch !IMPORTANT

### PR DESCRIPTION
**Pull request by royleibov**

### CODE REVIEW

**Comment by royleibov** [comment]
Can you have a look at the patch by version? Saw that https://github.com/huggingface/transformers/commit/4bb49d4e00a2fe6ecfb644c424dc8d88edc02590#diff-7c72c7b37efc6ac0f7537fb05562f66eaee01775f05c146f028eff5640f6f544 is from roughly September 27th, which corresponds to version 4.45.2 of transformers (https://pypi.org/project/transformers/#history)

**Comment by royleibov** [comment]
In latest feature added the ability to flag zipnn_hf(replace_local_file=True) to act in the old way.
Without it (default), the .znn file is loaded to a buffer ONCE for decompression and then immediately loaded to a state dict. The original .znn file is kept intact and no other I/O is done. With this method, each run will need to decompress the model from the top - but storage will stay minimal as we keep only compressed model.
NOTE: Added support for multiple shards and single file models, for safetensors, as well as everything else! I test it out a bit but further testing is needed to try and find its breaking points.
I believe this works though!

**Comment by royleibov** [comment]
Further note: To make this work added another monkey patch to a new function I found helpful (cached_file). This allows me to handle single file case.

**Comment by moshik1** [comment]
Looks Good! need to change also the README.md and HuggingFace.md, so the plugin will be better explained

**Comment by moshik1** [comment]
Approved, we deal with Readme later on

**Pull request merged**
